esphome:
  name: esp32c3-switches
  friendly_name: ESP32C3 Switches

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    # Replace this with 32-byte base64 encoded string.
    # Generate 32-byte base64 encoded string in https://esphome.io/components/api.html
    key: "redacted"

ota:
  password: "redacted"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32C3-Switches"
    password: "redacted"

captive_portal:


web_server:
  port: 80

switch:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    name: "Switch 1"

    
  - platform: gpio
    pin:
      number: GPIO1
      inverted: true
    name: "Switch 2"

  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
    name: "Switch 3"

  - platform: gpio
    pin:
      number: GPIO5
      inverted: true
    name: "Switch 4"

  - platform: gpio
    pin:
      number: GPIO6
      inverted: true
    name: "Switch 5"

    
  - platform: gpio
    pin:
      number: GPIO7
      inverted: true
    name: "Switch 6"

  - platform: gpio
    pin:
      number: GPIO10
      inverted: true
    name: "Switch 7"

  - platform: gpio
    pin:
      number: GPIO18
      inverted: true
    name: "Switch 8"